export const PRODUCTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/products'
export const ADMIN_PRODUCTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/products'
export const ORDERS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/shipping'
export const PAYMENTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/payments'
export const USER_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/api/v1'