export const WEBSITE_BASE_URL = 'https://online-grocery-store-sable.vercel.app/'
export const PRODUCTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/products'
export const ORDERS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/shipping'
export const NOTIFICATIONS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/notifications'
export const PAYMENTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/payments'
export const USER_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/api/v1'