export const WEBSITE_BASE_URL = 'http://localhost:3000'
export const PRODUCTS_BASEURL = 'http://localhost:5000/products'
export const ORDERS_BASEURL = 'http://localhost:5000/orders'
export const SHIPPING_BASEURL = 'http://localhost:5000/shipping'
export const NOTIFICATIONS_BASEURL = 'http://localhost:5000/notifications'
export const PAYMENTS_BASEURL = 'http://localhost:5000/payments'
export const USER_BASEURL = 'http://localhost:5000/api/v1'


// export const WEBSITE_BASE_URL = 'https://online-grocery-store-sable.vercel.app/'
// export const PRODUCTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/products'
// export const ORDERS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/orders'
// export const SHIPPING_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/shipping'
// export const NOTIFICATIONS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/notifications'
// export const PAYMENTS_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/payments'
// export const USER_BASEURL = 'https://online-grocery-store-7h2i-n2c4blg1v-mesho254.vercel.app/api/v1'